vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        image:
            uri_prefix: /media/images
            upload_destination: '%kernel.project_dir%/public/media/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer